openapi: 3.0.0
info:
  title: Case Seeds
  version: 2.0.0
  contact:
    name: 'Fatima och Emelie'
paths:
  /seeds:
    get:
      summary: Return all seeds from the database
      responses:
        '200':
          description: A list of seeds
        '204':
          description: A empty list
        '400':
          description: Could not implement your request
  /seeds/{id}:
    get:
      summary: Return information for a specific seed with a id
      parameters:
      - name: id
        in: path
        description: ID of seed to use
        required: true
        schema:
          type: array
          items:
            type: integer
      responses:
        '200':
          description: A description of a specific seed
        '404':
          description: ID does not exist
    delete:
      summary: Delete a seed from the database
      parameters:
      - name: id
        in: path
        description: ID of seed to use
        required: true
        schema:
          type: array
          items:
            type: integer
      responses:
        '200':
          description: Deleted
        '404':
          description: Could not delete
